-- MySQL Script generated by MySQL Workbench
-- Sun Nov 18 14:53:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema steamdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `steamdb` ;

-- -----------------------------------------------------
-- Schema steamdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `steamdb` DEFAULT CHARACTER SET utf8 ;
USE `steamdb` ;

-- -----------------------------------------------------
-- Table `steamdb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamdb`.`admin` ;

CREATE TABLE IF NOT EXISTS `steamdb`.`admin` (
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `firstName` VARCHAR(25) NOT NULL,
  `lastName` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamdb`.`platform`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamdb`.`platform` ;

CREATE TABLE IF NOT EXISTS `steamdb`.`platform` (
  `platformId` INT NOT NULL AUTO_INCREMENT,
  `platforms` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`platformId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamdb`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamdb`.`genre` ;

CREATE TABLE IF NOT EXISTS `steamdb`.`genre` (
  `genreId` INT NOT NULL,
  `genreName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genreId`, `genreName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steamdb`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `steamdb`.`game` ;

CREATE TABLE IF NOT EXISTS `steamdb`.`game` (
  `gameId` INT NOT NULL AUTO_INCREMENT,
  `gameName` VARCHAR(100) NOT NULL,
  `price` FLOAT NOT NULL,
  `userRating` INT NULL DEFAULT 5,
  `platformId` INT NOT NULL,
  `publisher` VARCHAR(50) NOT NULL,
  `genreId` INT NOT NULL,
  `imgUrl` VARCHAR(150) NOT NULL DEFAULT 'img/default.png',
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`gameId`),
  INDEX `fk_game_platform_idx` (`platformId` ASC),
  INDEX `fk_game_gameType1_idx` (`genreId` ASC),
  CONSTRAINT `fk_game_platform`
    FOREIGN KEY (`platformId`)
    REFERENCES `steamdb`.`platform` (`platformId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_gameType1`
    FOREIGN KEY (`genreId`)
    REFERENCES `steamdb`.`genre` (`genreId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
