# Team 3: 8-bit AL
# Students:	Christopher Caldwell
#			Thomas Krause
#			Muaath Alaraj
#			Doan Dinh


USE steamdb;
SET FOREIGN_KEY_CHECKS=0;


 # Insert values for the platform table...
INSERT INTO steamdb.platform (platformId, platforms)
VALUES
(1, "W"),
(2, "WML"),
(3, "WMS"),
(4, "WM");


 # Insert values for the genre table...
INSERT INTO steamdb.genre (genreId, genreName)
VALUES
(1, "Shooter"),
(2, "Fighting"),
(3, "Puzzle"),
(4, "Roleplaying"),
(5, "Simulation"),
(6, "Strategy"),
(7, "Sports"),
(8, "Platformer"),
(9, "Stealth"),
(10, "Virtual Reality");


 # Insert values for the game table...
INSERT INTO steamdb.game (gameName, price, userRating, publisher, platformId, genreId, imgUrl, description)
VALUES
("Tom Clancy's Rainbow Six® Siege", 10.49, 78, "Ubisoft", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/359550/header_alt_assets_3.jpg?t=1542377199", "Tom Clancy's Rainbow Six Siege is the latest installment of the acclaimed first-person shooter franchise developed by the renowned Ubisoft Montreal studio."),
("HELLGATE: London", 12.09, 67, "HanbitSoft Inc.", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/939520/header.jpg?t=1542337605", "The return of a sensational game! Hellgate is an action RPG game you have been waiting for. Since its first release Hellgate won the hearts of thousands of fans and now it's time to bring back memories and dip into the near future of 2038. For all mankind!"),
("Grand Theft Auto V", 29.99, 68, "Rockstar Games", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/271590/header.jpg?t=1539304955", "Los Santos is a city of bright lights, long nights and dirty secrets, and they don’t come brighter, longer or dirtier than in GTA Online: After Hours. The party starts now."),
("PLAYERUNKNOWN'S BATTLEGROUNDS", 29.99, 49, "PUBG Corporation", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/578080/header.jpg?t=1539300944", "PLAYERUNKNOWN'S BATTLEGROUNDS is a battle royale shooter that pits 100 players against each other in a struggle for survival. Gather supplies and outwit your opponents to become the last person standing."),
("Just Cause 4", 59.99, 89, "Square Enix", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/517630/header.jpg?t=1542389263", "Rogue agent Rico Rodriguez journeys to Solis, a huge South American world home of conflict, oppression and extreme weather conditions. Strap into your wingsuit, equip your fully customizable grappling hook, and get ready to bring the thunder!"),
("Borderlands 2", 19.99, 96, "2K, Aspyr (Mac), Aspyr (Linux)", 2, 1, "https://steamcdn-a.akamaihd.net/steam/apps/49520/header.jpg?t=1536253880", "A new era of shoot and loot is about to begin. Play as one of four new vault hunters facing off against a massive new world of creatures, psychos and the evil mastermind, Handsome Jack. Make new friends, arm them with a bazillion weapons and fight alongside them in 4 player co-op on a relentless quest for revenge and redemption across the undiscovered and unpredictable living planet."),
("DOOM", 19.99, 92, "Bethesda Softworks", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/379720/header.jpg?t=1533678963", "Now includes all three premium DLC packs (Unto the Evil, Hell Followed, and Bloodfall), maps, modes, and weapons, as well as all feature updates including Arcade Mode, Photo Mode, and the latest Update 6.66, which brings further multiplayer improvements as well as revamps multiplayer progression."),
("Far Cry® 5", 59.99, 66, "Ubisoft", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/552520/header.jpg?t=1534167982", "Welcome to Hope County, Montana, home to a fanatical doomsday cult known as Eden’s Gate. Stand up to cult leader Joseph Seed & his siblings, the Heralds, to spark the fires of resistance & liberate the besieged community."),
("Wolfenstein II: The New Colossus", 59.99, 67, "Bethesda-Soft", 1, 1, "https://steamcdn-a.akamaihd.net/steam/apps/612880/header.jpg?t=1532651329", "America, 1961. The assassination of Nazi General Deathshead was a short-lived victory. The Nazis maintain their stranglehold on the world. You are BJ Blazkowicz, aka “Terror-Billy,” member of the Resistance, scourge of the Nazi empire, and humanity’s last hope for liberty."),
("Left 4 Dead 2", 9.99, 96, "Valve", 3, 1, "https://steamcdn-a.akamaihd.net/steam/apps/550/header.jpg?t=1540300687", "Set in the zombie apocalypse, Left 4 Dead 2 (L4D2) is the highly anticipated sequel to the award-winning Left 4 Dead, the #1 co-op game of 2008. This co-operative action horror FPS takes you and your friends through the cities, swamps and cemeteries of the Deep South, from Savannah to New Orleans "),
("SOULCALIBUR VI", 59.99, 82, "BANDAI NAMCO Entertainment", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/544750/header.jpg?t=1540390529", "Bring more than your fists to the fight! Featuring all-new battle mechanics and characters, SOULCALIBUR VI marks a new era of the historic franchise. Welcome back to the stage of history!"),
("Lethal League Blaze", 19.99, 97, "Team Reptile", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/553310/header.jpg?t=1540733545", "Banging beats and mad style, Lethal League Blaze is the most intense ball game you can play online with up to 4 players."),
("Stick Fight: The Game", 4.99, 89, "Landfall", 4, 2, "https://steamcdn-a.akamaihd.net/steam/apps/674940/header.jpg?t=1509393964", "Stick Fight is a physics-based couch/online fighting game where you battle it out as the iconic stick figures from the golden age of the internet."),
("Street Fighter V", 19.99, 52, "Capcom", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/310950/header.jpg?t=1533675800", "Experience the intensity of head-to-head battles with Street Fighter® V! Choose from 16 iconic characters, then battle against friends online or offline with a robust variety of match options."),
("GORN", 19.99, 97, "Devolver Digital", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/578620/header.jpg?t=1535121305", "GORN is a ludicrously violent VR gladiator simulator, made by Free Lives, the developers of Broforce and Genital Jousting."),
("Gang Beasts", 19.99, 69, "Double Fine Presents", 3, 2, "https://steamcdn-a.akamaihd.net/steam/apps/285900/header.jpg?t=1534416166", "Gang Beasts is a silly multiplayer party game with surly gelatinous characters, brutal slapstick fight sequences, and absurd hazardous environments, set in the mean streets of Beef City."),
("Mortal Kombat X", 19.99, 74, "Warner Bros. Interactive Entertainment", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/307780/header.jpg?t=1499200501", "Experience the Next Generation of the #1 Fighting Franchise. Mortal Kombat X combines unparalleled, cinematic presentation with all new gameplay."),
("Injustice: Gods Among Us Ultimate Edition", 19.99, 85, "Warner Bros. Interactive Entertainment", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/242700/header.jpg?t=1461103774", "Injustice: Gods Among Us Ultimate Edition enhances the bold new franchise to the fighting game genre from NetherRealm Studios. Featuring six new playable characters, over 30 new skins, and 60 new S.T.A.R. Labs missions, this edition packs a punch."),
("TEKKEN 7", 39.99, 82, "BANDAI NAMCO Entertainment", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/389730/header.jpg?t=1538088819", "Discover the epic conclusion of the long-time clan warfare between members of the Mishima family. Powered by Unreal Engine 4, the legendary fighting game franchise fights back with stunning story-driven cinematic battles and intense duels that can be enjoyed with friends and rivals."),
("DRAGON BALL FighterZ", 59.99, 80, "BANDAI NAMCO Entertainment", 1, 2, "https://steamcdn-a.akamaihd.net/steam/apps/678950/header.jpg?t=1542398878", "DRAGON BALL FighterZ is born from what makes the DRAGON BALL series so loved and famous: endless spectacular fights with its all-powerful fighters."),
("Portal Bundle", 14.98, 98, "Valve", 3, 3, "https://steamcdn-a.akamaihd.net/steam/bundles/234/agkgmsr1oa7dduzk/header_586x192.jpg?t=1456861304", "The 'Perpetual Testing Initiative' has been expanded to allow you to design co-op puzzles for you and your friends!"),
("OneShot", 9.99, 98, "Degica", 4, 3, "https://steamcdn-a.akamaihd.net/steam/apps/420530/header.jpg?t=1527780127", "OneShot is a surreal top down Puzzle/Adventure game with unique gameplay capabilities. You are to guide a child through a mysterious world on a mission to restore its long-dead sun. The world knows you exist."),
("The Room", 5.99, 98, "Fireproof Games", 1, 3, "https://steamcdn-a.akamaihd.net/steam/apps/456750/header.jpg?t=1542102406", "Lured to a remote island, you find yourself confined within the rooms of an ominous mansion. You must draw upon all your puzzle-solving ability to navigate a series of trials devised by a mysterious figure known only as “The Craftsman”. Do you have what it takes to escape?"),
("Gorogoa", 14.99, 97, "Annapurna Interactive", 4, 3, "https://steamcdn-a.akamaihd.net/steam/apps/557600/header.jpg?t=1534541656", "Gorogoa is an elegant evolution of the puzzle genre, told through a beautifully hand-drawn story designed and illustrated by Jason Roberts. Winner of Debut Game at the 2018 BAFTA Games Awards, as well as Best Mobile Game and the Innovation Award at the GDC 2018 Choice Awards."),
("Celeste", 19.99, 97, "Matt Makes Games Inc.", 3, 3, "https://steamcdn-a.akamaihd.net/steam/apps/504230/header.jpg?t=1518176159", "Help Madeline survive her inner demons on her journey to the top of Celeste Mountain, in this super-tight platformer from the creators of TowerFall. Brave hundreds of hand-crafted challenges, uncover devious secrets, and piece together the mystery of the mountain."),
("Rakuen", 9.99, 97, "Laura Shigihara", 3, 3, "https://steamcdn-a.akamaihd.net/steam/apps/559210/header.jpg?t=1518516757", "A hospitalized Boy comes to terms with his own story by traveling with his Mom to a beautiful fantasy world; ultimately helping his fellow patients find closure by walking a mile in their shoes."),
("Marble It Up!", 19.99, 94, "Alvios, Inc., Marble It Up, LLC", 1, 3, "https://steamcdn-a.akamaihd.net/steam/apps/864060/header.jpg?t=1542386927", "Roll, bounce, and boost your way from skillful start to frame-perfect finish in Marble It Up! - the next generation of marble-rolling platformer. Chase the records of your friends and the world's best players through intricate, beautiful, mind-bending levels… Get Ready to Marble It Up!"),
("Trine Enchanted Edition", 14.99, 96, "FrozenByte", 3, 3, "https://steamcdn-a.akamaihd.net/steam/apps/35700/header.jpg?t=1530781124", "Three Heroes make their way through dangers untold in a fairytale world of great castles and strange machinery, featuring physics-based puzzles, beautiful sights and online co-op."),
("Fran Bow", 14.99, 96, "Killmonday Games AB", 3, 3, "https://steamcdn-a.akamaihd.net/steam/apps/362680/header.jpg?t=1534930016", "Fran Bow is a creepy adventure game that tells the story of Fran, a young girl struggling with a mental disorder and an unfair destiny."),
("Contradiction  Spot The Liar!", 9.99, 96, "Baggy Cat", 4, 3, "https://steamcdn-a.akamaihd.net/steam/apps/373390/header.jpg?t=1447375147", "Spot the lie and beat the liars in 'Contradiction' - the all-video murder mystery adventure!"),
("Epic Battle Fantasy 4", 11.99, 98, "Matt Roszak", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/265610/header.jpg?t=1448767949", "Epic Battle Fantasy 4 is a light-hearted turn-based RPG, heavily inspired by old classics like Final Fantasy and Golden Sun. You will battle through waves of adorable enemies, grow your characters, explore a diverse world, solve puzzles, and of course, save the world."),
("The Witcher® 3: Wild Hunt", 39.99, 97, "CD PROJEKT RED", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/292030/header.jpg?t=1541672778", "Experience the epic conclusion to the story of professional monster slayer, witcher Geralt of Rivia. As war rages on throughout the Northern Realms, you take on the greatest contract of your life — tracking down the Child of Prophecy, a living weapon that can alter the shape of the world."),
("South Park™: The Stick of Truth™", 29.99, 97, "Ubisoft", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/213670/header.jpg?t=1515609037", "From the perilous battlefields of the fourth-grade playground, a young hero will rise, destined to be South Park’s savior. From the creators of South Park, Trey Parker and Matt Stone, comes an epic quest to become… cool. Introducing South Park™: The Stick of Truth™.For a thousand years, the battle has been "),
("Stardew Valley", 14.99, 96, "Chucklefish", 3, 4, "https://steamcdn-a.akamaihd.net/steam/apps/413150/header.jpg?t=1541181309", "You've inherited your grandfather's old farm plot in Stardew Valley. Armed with hand-me-down tools and a few coins, you set out to begin your new life. Can you learn to live off the land and turn these overgrown fields into a thriving home?"),
("Ni no Kuni™ II: Revenant Kingdom", 59.99, 81, "BANDAI NAMCO Entertainment", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/589360/header.jpg?t=1537197193", "Join the young king Evan as he sets out on an epic quest to found a new kingdom and, with the help of some new friends, unite his world, saving its people from a terrible evil."),
("Divinity: Original Sin 2  Definitive Edition", 44.99, 93, "Larian Studios", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/435150/header.jpg?t=1539352146", "The eagerly anticipated sequel to the award-winning RPG. Gather your party. Master deep, tactical combat. Join up to 3 other players - but know that only one of you will have the chance to become a God."),
("MONSTER HUNTER: WORLD", 59.99, 55, "CAPCOM Co., Ltd.", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/582010/header.jpg?t=1542327310", "Welcome to a new world! In Monster Hunter: World, the latest installment in the series, you can enjoy the ultimate hunting experience, using everything at your disposal to hunt monsters in a new world teeming with surprises and excitement."),
("Fallout 4", 59.99, 68, "Bethesda Softworks", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/377160/header.jpg?t=1533676954", "Bethesda Game Studios, the award-winning creators of Fallout 3 and The Elder Scrolls V: Skyrim, welcome you to the world of Fallout 4 – their most ambitious game ever, and the next generation of open-world gaming."),
("The Elder Scrolls V: Skyrim Special Edition", 39.99, 85, "Bethesda Softworks", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/489830/header.jpg?t=1533676854", "Winner of more than 200 Game of the Year Awards, Skyrim Special Edition brings the epic fantasy to life in stunning detail. The Special Edition includes the critically acclaimed game and add-ons with all-new features like remastered art and effects, volumetric god rays, dynamic depth of field, screen-space "),
("Two Worlds II HD", 19.99, 57, "Topware Interactive, ACE", 1, 4, "https://steamcdn-a.akamaihd.net/steam/apps/7520/header.jpg?t=1535036908", "Check out the new Velvet Edition bundle including both Two Worlds II and Pirates of the Flying Fortress DLC."),
("Planet Coaster", 44.99, 88, "Frontier Developments", 1, 5, "https://steamcdn-a.akamaihd.net/steam/apps/493340/header.jpg?t=1542366395", "Planet Coaster® - the future of coaster park simulation games has arrived! Surprise, delight and thrill incredible crowds as you build your coaster park empire - let your imagination run wild, and share your success with the world."),
("Farming Simulator 19", 34.99, 85, "Focus Home Interactive", 4, 5, "https://steamcdn-a.akamaihd.net/steam/apps/787860/header.jpg?t=1542032572", "The best-selling franchise takes a giant leap forward with a complete overhaul of the graphics engine, offering the most striking and immersive visuals and effects, along with the deepest and most complete farming experience ever."),
("Assetto Corsa Ultimate Edition", 39.88, 87, "Kunos Simulazioni", 1, 5, "https://steamcdn-a.akamaihd.net/steam/apps/244210/header.jpg?t=1519574042", "Assetto Corsa v1.16 introduces the new 'Laguna Seca' laser-scanned track, 7 new cars among which the eagerly awaited Alfa Romeo Giulia Quadrifoglio! Check the changelog for further info!"),
("Cities: Skylines", 29.99, 91, "Paradox Interactive", 3, 5, "https://steamcdn-a.akamaihd.net/steam/apps/255710/header.jpg?t=1540369457", "Cities: Skylines is a modern take on the classic city simulation. The game introduces new game play elements to realize the thrill and hardships of creating and maintaining a real city whilst expanding on some well-established tropes of the city building experience."),
("Two Point Hospital", 34.99, 80, "SEGA", 3, 5, "https://steamcdn-a.akamaihd.net/steam/apps/535930/header.jpg?t=1541083998", "Design stunning hospitals, cure peculiar illnesses and manage troublesome staff as you spread your budding healthcare organisation across Two Point County."),
("Euro Truck Simulator 2", 19.99, 96, "SCS Software", 3, 5, "https://steamcdn-a.akamaihd.net/steam/apps/227300/header.jpg?t=1541770236", "Travel across Europe as king of the road, a trucker who delivers important cargo across impressive distances! With dozens of cities to explore from the UK, Belgium, Germany, Italy, the Netherlands, Poland, and many more, your endurance, skill and speed will all be pushed to their limits."),
("War Thunder", 0, 79, "Gaijin Entertainment", 3, 5, "https://steamcdn-a.akamaihd.net/steam/apps/236390/header.jpg?t=1540898307", "War Thunder is the most comprehensive free-to-play, cross-platform, MMO military game for Windows, Linux, Mac and PlayStation®4 dedicated to aviation, armoured vehicles, and naval craft from World War II and the Cold War."),
("Elite Dangerous", 29.99, 67, "Frontier Developments", 1, 5, "https://steamcdn-a.akamaihd.net/steam/apps/359320/header.jpg?t=1524749561", "Take control of your own starship in a cutthroat galaxy. Elite Dangerous brings gaming’s original open world adventure into the modern generation with a connected galaxy, evolving narrative and the entirety of the Milky Way re-created at its full galactic proportions."),
("The Sims™ 3", 19.99, 81, "Electronic Arts", 1, 5, "https://steamcdn-a.akamaihd.net/steam/apps/47890/header.jpg?t=1523572246", "Ready to live a freer, more creative life? In The Sims™ 3, you can let your fantasies run wild as you design your ideal world. Start with your Sim, refining each shape, color and personality trait until you get the precise person that pleases you. Design your dream home, but don’t let a grid limit you; place, rotate and stack furniture and walls freely and to your heart’s content."),
("Kerbal Space Program", 39.99, 90, "Private Division", 3, 5, "https://steamcdn-a.akamaihd.net/steam/apps/220200/header.jpg?t=1542072020", "Kerbal Space Program 1.5: Dressed for Success is now available.With this update both the base game and the expansion are getting their share of enhancements. With that in mind, a key aspect in this update is the optimization and fresh makeover of various parts, as well the improvement of the burn "),
("Total War: WARHAMMER II", 59.99, 85, "SEGA", 1, 6, "https://steamcdn-a.akamaihd.net/steam/apps/594570/header.jpg?t=1541517353", "Strategy gaming perfected. A breath-taking campaign of exploration, expansion and conquest across a fantasy world. Turn-based civilisation management and real-time epic strategy battles with thousands of troops and monsters at your command."),
("Crusader Kings II: Collection", 19.99, 94, "Paradox Interactive", 3, 6, "https://steamcdn-a.akamaihd.net/steam/apps/203770/header_alt_assets_0.jpg?t=1542147600", "Explore one of the defining periods in world history in an experience crafted by the masters of Grand Strategy."),
("Sid Meier’s Civilization® VI", 59.99, 66, "2K, Aspyr (Mac), Aspyr (Linux)", 3, 6, "https://steamcdn-a.akamaihd.net/steam/apps/289070/header.jpg?t=1541781497", "Civilization VI offers new ways to interact with your world, expand your empire across the map, advance your culture, and compete against history’s greatest leaders to build a civilization that will stand the test of time. Play as one of 20 historical leaders including Roosevelt (America) and Victoria (England)."),
("Age of Empires II HD", 19.99, 94, "Microsoft Studios", 1, 6, "https://steamcdn-a.akamaihd.net/steam/apps/221380/header.jpg?t=1534437316", "Age of Empires II has been re-imagined in high definition with new features, trading cards, improved AI, workshop support, multiplayer, Steamworks integration and more!"),
("Stellaris", 39.99, 76, "Paradox Interactive", 3, 6, "https://steamcdn-a.akamaihd.net/steam/apps/281990/header.jpg?t=1541514254", "Explore a vast galaxy full of wonder! Paradox Development Studio, makers of the Crusader Kings and Europa Universalis series presents Stellaris, an evolution of the grand strategy genre with space exploration at its core."),
("Arma 3", 39.99, 89, "Bohemia Interactive", 1, 6, "https://steamcdn-a.akamaihd.net/steam/apps/107410/header.jpg?t=1524502112", "Experience true combat gameplay in a massive military sandbox. Deploying a wide variety of single- and multiplayer content, over 20 vehicles and 40 weapons, and limitless opportunities for content creation, this is the PC’s premier military game. Authentic, diverse, open - Arma 3 sends you to war."),
("STAR WARS™ Empire at War  Gold Pack", 19.99, 93, "LucasArts, Lucasfilm, Disney Interactive", 1, 6, "https://steamcdn-a.akamaihd.net/steam/apps/32470/header.jpg?t=1524018520", "Command or corrupt an entire galaxy in the definitive Star Wars strategy collection. It is a time of galactic civil war. Will you take up the reins of the Rebellion, assume control of the Empire, or rule the Star Wars Underworld?"),
("Tropico 6", 49.99, 93, "Kalypso Media", 3, 6, "https://steamcdn-a.akamaihd.net/steam/apps/492720/header.jpg?t=1542302061", "El Presidente is back! Prove yourself once again as a feared dictator or peace-loving statesman on the island state of Tropico and shape the fate of your very own banana republic through four distinctive eras."),
("SPORE™", 19.99, 87, "Electronic Arts", 1, 6, "https://steamcdn-a.akamaihd.net/steam/apps/17390/header.jpg?t=1490108896", "From Single Cell to Galactic God, evolve your creature in a universe of your own creations. Play through Spore's five evolutionary stages: Cell, Creature, Tribe, Civilization, and Space. Each stage has its own unique style, challenges, and goals."),
("Total War™: ROME II  Emperor Edition", 59.95, 67, "SEGA", 4, 6, "https://steamcdn-a.akamaihd.net/steam/apps/214950/header.jpg?t=1540813671", "About Total War: ROME II - Emperor Edition:Emperor Edition is the definitive edition of ROME II, featuring an improved politics system, overhauled building chains, rebalanced battles and improved visuals in both campaign and battle."),
("NBA 2K19", 59.99, 21, "2K", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/841370/header.jpg?t=1542230615", "NBA 2K celebrates 20 years of redefining what sports gaming can be. NBA 2K19 continues to push limits as it brings gaming one step closer to real-life basketball excitement and culture."),
("Rocket League®", 19.99, 91, "Psyonix, Inc.", 3, 7, "https://steamcdn-a.akamaihd.net/steam/apps/252950/header.jpg?t=1541456669", "Soccer meets driving once again in the long-awaited, physics-based multiplayer-focused sequel to Supersonic Acrobatic Rocket-Powered Battle-Cars! Choose a variety of high-flying vehicles equipped with huge rocket boosters to score amazing aerial goals and pull-off incredible game-changing saves!"),
("F1 2018", 59.99, 75, "Codemasters", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/737800/header.jpg?t=1539687513", "MAKE HEADLINES in F1® 2018. F1® 2018 is the official videogame of the 2018 FIA FORMULA ONE WORLD CHAMPIONSHIP™. Become immersed in the world of Formula 1® more than ever before.Build your reputation both on and off the track, with time-pressured media interviews that influence your F1 "),
("Golf It!", 8.99, 77, "Perfuse Entertainment", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/571740/header.jpg?t=1533757652", "Golf It! is a multiplayer Minigolf game with focus on a dynamic, fun and creative multiplayer experience. One of the most exciting features is a Multiplayer Editor, where you can build and play custom maps together with your friends."),
("Draft Day Sports: Pro Basketball 2019", 34.99, 58, "Wolverine Studios", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/971900/header.jpg?t=1542119203", "Draft Day Sports: Pro Basketball 2019 puts you in the role of general manager of your favorite professional basketball team. Every decision can be made by you from drafting, trading, signing free agents all the way to making each substitution to lead your team to championship glory and becoming a dynasty."),
("Monster Energy Supercross  The Official Videogame", 49.99, 65, "Milestone S.r.l.", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/882020/header.jpg?t=1540983595", "All the action, all the battle and all the feeling of the 2018 Monster Energy AMA Supercross Championship! Live the life of a real rider testing your skills in the Compound, facing different challenges, managing your agenda and attracting new sponsors to increase the fame and unlock new items!"),
("Blood Bowl 2  Legendary Edition", 44.99, 70, "Focus Home Interactive", 4, 7, "https://steamcdn-a.akamaihd.net/steam/apps/236690/header.jpg?t=1534163480", "Blood Bowl 2 smashes Warhammer and American football together, in an explosive cocktail of turn-based strategy, humour and brutality, adapted from Games Workshop’s famous boardgame."),
("Hunting Simulator", 39.99, 39, "Focus Home Interactive", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/585080/header.jpg?t=1512057824", "Live the adventure of the hunt, from Alberta to Texas, France, Colorado or Scotland. Play single or multiplayer, choose your hunting gear and firearms of choice, including Browning® and Winchester® models, and master tracking 37 different animal species each with realistic behaviours."),
("Franchise Hockey Manager 5", 39.99, 41, "Out of the Park Developments", 4, 7, "https://steamcdn-a.akamaihd.net/steam/apps/880380/header.jpg?t=1539020046", "Franchise Hockey Manager 5 is the only sports strategy game licensed by the NHL ® , including the real clubs, awards, and trophies associated with the greatest hockey league in the world. FHM 5 allows you to build your hockey franchise into a perennial Stanley Cup winner YOUR way, in the current 2018-"),
("Super Mega Baseball 2", 29.99, 81, "Metalhead Software Inc.", 1, 7, "https://steamcdn-a.akamaihd.net/steam/apps/414870/header.jpg?t=1540504536", "The critically acclaimed Super Mega Baseball series is back with new visuals, deep team and league customization, and online multiplayer modes."),
("Super Meat Boy", 14.99, 94, "Team Meat", 3, 8, "https://steamcdn-a.akamaihd.net/steam/apps/40800/header.jpg?t=1540402690", "The infamous, tough-as-nails platformer comes to Steam with a playable Head Crab character (Steam-exclusive)!"),
("Tunche", 24.99, 85, "HypeTrain Digital", 1, 8, "https://steamcdn-a.akamaihd.net/steam/apps/887450/header.jpg?t=1542204988", "Tunche is a charming, hand-drawn adventure that blends classic beat'em up brawler gameplay with roguelike elements, 4-player co-op and a pinch of shaman witchcraft. Master the ancient magical arts, defeat epic bosses and unravel the secrets of the mysterious Amazonian jungle!"),
("Crash Bandicoot™ N. Sane Trilogy", 39.99, 93, "Activision", 1, 8, "https://steamcdn-a.akamaihd.net/steam/apps/731490/header.jpg?t=1530311978", "Your favorite marsupial, Crash Bandicoot™, is back! He’s enhanced, entranced and ready-to-dance with the N. Sane Trilogy. Relive all your favorite moments in Crash Bandicoot™, Crash Bandicoot™ 2: Cortex Strikes Back and Crash Bandicoot™ 3: Warped, now in fully-remastered graphical glory!"),
("DEEP SPACE | SpacePlatformer", 4.99, 50, "OraMonkey", 1, 8, "https://steamcdn-a.akamaihd.net/steam/apps/853040/header.jpg?t=1528282130", "You think you can handle everything? Then grab a gun, jump at the helm of the ship and get ready for hardcore adventures in Deep Space!"),
("Cuphead", 19.99, 95, "Studio MDHR Entertainment Inc.", 4, 8, "https://steamcdn-a.akamaihd.net/steam/apps/268910/header.jpg?t=1539967486", "Cuphead is a classic run and gun action game heavily focused on boss battles. Inspired by cartoons of the 1930s, the visuals and audio are painstakingly created with the same techniques of the era, i.e. traditional hand drawn cel animation, watercolor backgrounds, and original jazz recordings."),
("Hollow Knight", 14.99, 94, "Team Cherry", 3, 8, "https://steamcdn-a.akamaihd.net/steam/apps/367520/header.jpg?t=1537843484", "Forge your own path in Hollow Knight! An epic action adventure through a vast ruined kingdom of insects and heroes. Explore twisting caverns, battle tainted creatures and befriend bizarre bugs, all in a classic, hand-drawn 2D style."),
("Mega Man 11", 29.99, 90, "Capcom", 1, 8, "https://steamcdn-a.akamaihd.net/steam/apps/742300/header.jpg?t=1541093532", "Mega Man is back! The newest entry in this iconic series blends classic, challenging 2D platforming action with a fresh new visual style. The new Double Gear system boosts Mega Man's speed and power for a new twist to the satisfying gameplay the series is known for."),
("Super Lucky's Tale", 19.99, 89, "Microsoft Studios", 1, 8, "https://steamcdn-a.akamaihd.net/steam/apps/847360/header.jpg?t=1538459975", "A delightful, playground platformer for all ages that follows Lucky, the ever-optimistic, energetic, and lovable hero, on his quest to find his inner strength and help his sister rescue the Book of Ages from Jinx. Jinx is the scheming and mysterious villain trying to reshape the world, but for what reason?"),
("Ori and the Blind Forest: Definitive Edition", 19.99, 95, "Microsoft Studios", 1, 8, "https://steamcdn-a.akamaihd.net/steam/apps/387290/header.jpg?t=1516735183", "“Ori and the Blind Forest” tells the tale of a young orphan destined for heroics, through a visually stunning Action-Platformer crafted by Moon Studios."),
("Ultimate Chicken Horse", 14.99, 94, "Clever Endeavour Games", 3, 8, "https://steamcdn-a.akamaihd.net/steam/apps/386940/header.jpg?t=1539194459", "Ultimate Chicken Horse is a party platformer game where you build the level as you play, placing traps and hazards to screw your friends over, but trying not to screw yourself."),
("HITMAN™ 2", 0, 78, "Warner Bros Interactive Entertainment", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/863550/header.jpg?t=1542139562", "Travel the globe and track your targets across exotic sandbox locations in HITMAN™ 2. From sun-drenched streets to dark and dangerous rainforests, nowhere is safe from the world’s most creative assassin, Agent 47 in the ultimate spy thriller story."),
("Thief Simulator", 19.99, 79, "PlayWay S.A.", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/704850/header.jpg?t=1541943673", "Become the best thief. Gather intel, steal things and sell them to buy hi-tech equipment. Do everything that a real thief does."),
("Shadow of the Tomb Raider", 59.99, 65, "Square Enix", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/750920/header.jpg?t=1542233844", "As Lara Croft races to save the world from a Maya apocalypse, she must become the Tomb Raider she is destined to be."),
("The Deus Ex Collection", 62.24, 76, "Square Enix", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/337000/header.jpg?t=1513077042", "Now an experienced covert operative, Adam Jensen is forced to operate in a world that has grown to despise his kind. Armed with a new arsenal of state-of-the-art weapons and augmentations, he must choose the right approach, along with who to trust, in order to unravel a vast worldwide conspiracy."),
("Assassin's Creed® Odyssey", 59.99, 77, "Ubisoft", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/812140/header.jpg?t=1540836192", "Choose your fate in Assassin's Creed® Odyssey. From outcast to living legend, embark on an odyssey to uncover the secrets of your past and change the fate of Ancient Greece."),
("Sniper Elite 4", 59.99, 85, "Rebellion", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/312660/header.jpg?t=1519660126", "Discover unrivalled sniping freedom in the largest and most advanced World War 2 shooter ever built. Experience tactical third-person combat, gameplay choice and epic longshots across gigantic levels as you liberate wartime Italy from the grip of Fascism."),
("Tom Clancy's Ghost Recon® Wildlands", 49.99, 73, "Ubisoft", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/460930/header.jpg?t=1537950593", "Create a team with up to 3 friends in Tom Clancy’s Ghost Recon® Wildlands and enjoy the ultimate military shooter experience set in a massive, dangerous, and responsive open world."),
("Shadow Tactics: Blades of the Shogun", 39.99, 95, "Daedalic Entertainment", 3, 9, "https://steamcdn-a.akamaihd.net/steam/apps/418240/header.jpg?t=1538386937", "Shadow Tactics is a hardcore tactical stealth game set in Japan around the Edo period. A new Shogun seizes power over Japan and enforces nationwide peace. In his battle against conspiracy and rebellion, he recruits five specialists with extraordinary skills for assassination, sabotage and espionage."),
("Phantom Doctrine", 39.99, 73, "Good Shepherd Entertainment", 1, 9, "https://steamcdn-a.akamaihd.net/steam/apps/559100/header.jpg?t=1541162287", "The year is 1983. The world teeters on the verge of destruction as the Cold War tightens its icy grip. East or West: trust no one, question everything. The fate of humanity rests in your hands as you pit spy versus spy in tactical Phantom Doctrine."),
("Thief", 29.99, 70, "Square Enix", 4, 9, "https://steamcdn-a.akamaihd.net/steam/apps/239160/header.jpg?t=1530655519", "Garrett, the Master Thief, steps out of the shadows into the City. In this treacherous place, where the Baron’s Watch spreads a rising tide of fear and oppression, his skills are the only things he can trust. Even the most cautious citizens and their best-guarded possessions are not safe from his reach."),
("The Elder Scrolls V: Skyrim VR", 59.99, 82, "Bethesda Softworks", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/611670/header.jpg?t=1524178401", "A true, full-length open-world game for VR has arrived from Bethesda Game Studios. Skyrim VR reimagines the complete epic fantasy masterpiece with an unparalleled sense of scale, depth, and immersion. Skyrim VR also includes all official add-ons."),
("Beat Saber", 19.99, 97, "Beat Games", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/620980/header.jpg?t=1528748839", "Beat Saber is a VR rhythm game where your goal is to slash the beats which perfectly fit into precisely handcrafted music."),
("SUPERHOT VR", 24.99, 89, "SUPERHOT Team", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/617830/header.jpg?t=1541527888", "Lose track of what’s real. Commit yourself, body and mind. Confront the evocative, elegantly brutal world of SUPERHOT VR. Enemies pouring into the room from all sides, dozens of bullets coursing through the air... Wait. Something seems different in here..."),
("Job Simulator", 19.99, 83, "Owlchemy Labs", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/448280/header.jpg?t=1524002048", "In a world where robots have replaced all human jobs, step into the 'Job Simulator' to learn what it was like 'to job'."),
("Rick and Morty: Virtual Rickality", 29.99, 74, "Adult Swim Games", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/469610/header.jpg?t=1510772114", "Rick and Morty: Virtual Rick-ality smashes together the absolute VR chaos of the award-winning Job Simulator with the ridiculous, all-out, take-no-prisoners comedy of Rick and Morty."),
("Tilt Brush", 19.99, 97, "Google", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/327140/header.jpg?t=1533672778", "Tilt Brush lets you paint in 3D space with virtual reality. Unleash your creativity with three-dimensional brush strokes, stars, light, and even fire. Your room is your canvas. Your palette is your imagination. The possibilities are endless."),
("Budget Cuts", 29.99, 70, "Neat Corporation", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/400940/header.jpg?t=1539368575", "Budget Cuts is a VR stealth game where you dexterously zip, sneak or rambo your way forward through thrilling, oil-splatter filled combat!"),
("Space Pirate Trainer", 14.99, 95, "I-Illusions", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/418650/header.jpg?t=1526302310", "Space Pirate Trainer is the official trainer for wannabe space pirates in VR. Pick up your blasters, put on your sneakers, and dance your way into the Space Pirate Trainer hall of fame."),
("VR Kanojo", 49.99, 78, "ILLUSION", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/751440/header.jpg?t=1533290218", "This is Steam version.Looking for a unique VR experience? Well, look no further!In VR Kanojo, you can hang out with the lovely girl-next-door, Sakura Yuuhi. You'll practically feel her breath on your cheek and the warmth of her fingers on your arm as you laugh and talk the day away."),
("Surgeon Simulator: Experience Reality", 19.99, 63, "Bossa Studios", 1, 10, "https://steamcdn-a.akamaihd.net/steam/apps/518920/header.jpg?t=1526556421", "Surgeon Simulator is bringing the ER to VR! The most critically acclaimed and infamous surgery simulation game as you have never seen it before! Featuring all of the surgeries and twisted humour of the original favourite plus a few new surprises...");


 # Insert values for the admin table...
INSERT INTO steamdb.admin (username, password, firstName, lastName)
VALUES
("admin", "secret", "Admin", "Admin");


SET FOREIGN_KEY_CHECKS=1;

